apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deploymentname }}
  namespace: default
  labels:
    chart: "minecraftaandb"
spec:
  replicas: 1
  selector:
    matchLabels:
      bb: {{ .Values.deploymentname }}
  template:
    metadata:
      labels:
        bb: {{ .Values.deploymentname }}
    spec:
      containers:
      - name: {{ .Values.deploymentname }}
        image: "{{ .Values.imageRepository }}:{{ default "latest" .Values.imageTag }}"
        resources:
          limits:
            memory: "{{ .Values.Resources.memoryLimit }}"
            cpu: "{{ .Values.Resources.cpuLimit }}"
        volumeMounts:
        - name: "minecraftdata"
          mountPath: {{ .Values.Persistence.MountPath }}
      volumes:
      - name: "minecraftdata"
      {{- if .Values.Persistence.Enabled }}
        persistentVolumeClaim:
          claimName: {{ .Values.Persistence.VolumeName }}
      {{- else }}
          emptyDir: {}
      {{- end }}
