apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.deploymentname }}-svc"
  namespace: default
spec:
  type: {{ .Values.service.type }}
  selector:
    bb: {{ .Values.deploymentname }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}