apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.metadata.name }}-deployment
  namespace: {{ .Values.metadata.namespace }}
  labels:
    chart: {{ .Chart.name }}
    app: {{ .Values.metadata.name }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        bb: {{ .Values.metadata.name }}
    spec:
      containers:
      - name: {{ .Values.metadata.name }}
        image: "{{ .Values.imageRepository }}:{{ default "latest" .Values.imageTag }}"
        ports:
        - containerPort: 80