apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.metadata.name }}-svc
  namespace: {{ .Values.metadata.namespace }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Values.metadata.name }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}
    nodePort: {{ .Values.service.nodePort }}