apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: default
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: {{ .Values.spec.metadata.namespace }}
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: "*"
    chart: bettergrafana
    # https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/application.yaml
    helm:
      # valueFiles:
      # - values-grafana.yaml
      values: |
        dashboards:
          default:
            azuresql:
              file: dashboards/azuresql.json
              datasource: prometheus
        ingress:
          enabled: true
          annotations: {}
            kubernetes.io/ingress.class: nginx
            # kubernetes.io/tls-acme: "true"
          labels: {}
          path: /
          pathType: Prefix
          hosts:
            - grafana.homelab.box
 
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
