apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: helloworld-ing
  annotations:
    kubernetes.io/ingress.class: "nginx"
  namespace: default
spec:
  ingressClassName: "nginx"
  rules:
  - host: mortyn.homelab.box
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: {{ .Values.metadata.name }}-svc
            port: 
              number: {{ .Values.service.port }}
        