apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-myserviceb
  annotations:
    # use the shared ingress-nginx
    kubernetes.io/ingress.class: "nginx"
  namespace: default
spec:
  rules:
  - host: mortyn.homelab.box
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Values.metadata.name }}-svc
          servicePort: {{ .Values.service.port }}