apiVersion: apps/v1
kind: Deployment
metadata:
  name: piclustermetrics-deployment
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels: # labels to select/identify the deployment
        app: {{ .Values.name }}
    spec:     # pod spec                  
      containers: 
      - name: {{ .Values.name }}
        image: {{ .Values.image.repository }} # image we pushed
        ports:
        - containerPort: 8080