apiVersion: apps/v1
kind: Deployment
metadata:
  name: piclustermetrics-deployment
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      run: {{ .Values.name }}
  template:
    metadata:
      labels:
        run: {{ .Values.name }}
    spec:
      containers:
      - name: {{ .Values.name }}
        image: {{ .Values.image.repository }}
        ports:
        - containerPort: 8080