apiVersion: v1
kind: Pod
metadata:
  name: {{ include "piclustermetrics.fullname" . }}
spec:
  containers:
  - image: nginx:latest
    name: nginx-container
    tty: true
    stdin: true
    volumeMounts:
    - mountPath: /test-pd
      name: test-volume
  volumes:
  - name: test-volume
    hostPath:
      # directory location on host
      path: /usr/bin
      # this field is optional
      type: Directory