apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: networkmon
  namespace: argocd
  finalizers: []
spec:
  destination:
    namespace: {{ .Values.spec.metadata.namespace }}
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: "*"
    chart: networkmon
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
