apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deploymentname }}
  namespace: default
  labels:
    chart: "comfy"
spec:
  replicas: 1
  selector:
    matchLabels:
      bb: {{ .Values.deploymentname }}
  template:
    metadata:
      labels:
        bb: {{ .Values.deploymentname }}
    spec:
      volumes:
      - name: serverconfig-cm
        configMap:
          name: serverconfig-cm
      - name: datadir
      {{- if .Values.persistence.dataDir.enabled }}
        persistentVolumeClaim:
        {{- if .Values.persistence.dataDir.existingClaim }}
          claimName: {{ .Values.persistence.dataDir.existingClaim }}
        {{- else }}
          claimName: {{ .Values.deploymentname }}-datadir
        {{- end }}
      {{- else }}
        emptyDir: {}
      {{- end }}
      {{- range .Values.extraVolumes }}
      {{- toYaml .volumes | nindent 6 }}
      {{- end }}
      containers:
      - name: {{ .Values.deploymentname }}
        image: "{{ .Values.imageRepository }}:{{ default "latest" .Values.imageTag }}"
        readinessProbe:
          tcpSocket:
            port: 25565
          initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
          failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
          successThreshold: {{ .Values.readinessProbe.successThreshold }}
          timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
        livenessProbe:
          tcpSocket:
            port: 25565
          initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
          failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
          successThreshold: {{ .Values.livenessProbe.successThreshold }}
          timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
        resources:
          limits:
            memory: "{{ .Values.Resources.memoryLimit }}"
            cpu: "{{ .Values.Resources.cpuLimit }}"
        volumeMounts:
        - name: datadir
          mountPath: /minecraft
        {{- range .Values.extraVolumes }}
        {{- toYaml .volumeMounts | nindent 8 }}
        {{- end }}
