kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.deploymentname }}-datadir
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 40Gi